language: objective-c
osx_image: xcode9
podfile: Example/Podfile
script:
 - xcodebuild build -project Example/ExampleBootstrap.xcodeproj -scheme ExampleBootstrapTests -destination 'platform=iOS Simulator,OS=11.0,name=iPhone 5s' build test | xcpretty -c --test --color
 
