language: objective-c
osx_image: xcode9
script:
 - xcodebuild build -project Example/ExampleBootstrap.xcodeproj -scheme ExampleBootstrap -destination 'platform=iOS Simulator,OS=11.0,name=iPhone 5s' build test | xcpretty -c --test --color
