language: objective-c
osx_image: xcode9
#podfile: Example/Podfile
#pod install
before_install:
- pod install --project-directory=Example
script:
 - xcodebuild build -project ExampleBootstrap.xcodeproj -scheme ExampleBootstrapTests -destination 'platform=iOS Simulator,OS=11.0,name=iPhone 5s' | xcpretty -c --test --color
 
